### ISSUE TITLE
我在eval发布的权重时出现了一些问题，能否提供一下eval的方法

### ISSUE THREAD

**Issue by comedy0913** [pengzhiliang/G2SD#8]
在我对您在Google Drive上发布的权重文件进行eval的时候出现了一些错误，出现了大面积的准确率为0的情况，这是我的命令

python main_finetune_dis.py --eval --resume "/data_hdd1/wjl/checkpoint-199.pth" --model vit_small_patch16 --batch_size 16 --data_path '/data/ILSVRC2012/ImageNet1000' --eval_data_path '/data/ILSVRC2012/ImageNet1000' --teacher_path  '/data_hdd1/wjl/mae_finetuned_vit_base.pth' --finetune "/data_hdd1/wjl/checkpoint-199.pth" --teacher_model vit_base_patch16

checkpoint-199.pth下载自google drive中的vit_s_gd_sd_classification，事实上我在fintune的时候也遇到了同样的问题，期待您的回复，非常感谢
![屏幕截图 2024-04-11 222022](https://github.com/pengzhiliang/G2SD/assets/62831199/0b36c9b1-78b4-4d0a-9a49-c7601e11d276)

**Comment by Vickeyhw** [comment]
@comedy-13 --eval_data_path  path_ImageNet/val ImageNet验证集有50000张图片，数据数量不对

**Comment by comedy0913** [comment]
没问题了，非常感谢您，因为我mae的代码路径就是这个，再加上没有报错，确实没有注意到，非常感谢您的解答。
